#!/bin/bash

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

API_URL="https://pokeapi.co/api/v2/pokemon"


OUTPUT_DIR="pokemon_data"
mkdir -p "$OUTPUT_DIR"

# Loop through each Pokémon
for name in "${POKEMONS[@]}"; do
    echo "Fetching data for $name..."
    curl -s "${API_URL}/${name}" -o "${OUTPUT_DIR}/${name}.json"
    if jq empty "${OUTPUT_DIR}/${name}.json" 2>/dev/null; then
        echo "Saved ${name}.json"
    else
        echo "Failed to fetch data for $name"
        rm -f "${OUTPUT_DIR}/${name}.json"
    fi

    sleep 2
done
