#!/bin/bash

jq -r '.results[] | "\(.name),\(.type),\(.height),\(.weight)"' data.json |
awk -F',' '{ printf "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.", NR, $1, $2 }' |
sed -e 's/pokemon/POKÉMON/g' -e 's/\/$//'

